baseurl = "https://cubbic.github.io/"
languageCode = "en-us"
title = "Why not to "
theme = "beautifulhugo"
pygmentsUseClasses = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  logo = "img/avatar-icon.png"
  subtitle = "Build a beautiful and simple website in minutes"

[Author]
  name = "cubbic"
  email = "danpopa1998@gmail.com"

  github = "cubbic"
  twitter = "Cubbium"


[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
